### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.sma-em#110] opened 2021-01-06 20:21 UTC
**Describe the bug**  
I faced problem now three times that I don't get any updates from SMA EM. Unfortunately I see it only days after, so no log. Connected indicator stays true.

![image](https://user-images.githubusercontent.com/15956503/103815633-f063f880-5063-11eb-9b7b-0ca340a1a405.png)

Are you aware of this issue?

**Comment by Flauschi83** [comment] 2021-01-11 11:08
same problem here.
It exists since last November I think.
Only possibility is to restart the adapter every minute.

**Comment by DutchmanNL** [comment] 2021-01-18 21:01
please retest with new version

**Comment by Flauschi83** [comment] 2021-01-18 22:26
I installed 0.6.1-beta.0 adapter restarted...deleted the cron restart and after a minute again, nothing:

![image](https://user-images.githubusercontent.com/46086597/104967733-65c8b500-59e4-11eb-8c42-8a144ac76152.png)


the easiest check is always the red SMA Tick Counter.
A restart solves the issue...therefore I will switch back to a minutly cron restart....the disconnect happens after roughly 58 seconds.

**Comment by Flauschi83** [comment] 2021-01-20 21:43
@DutchmanNL could you please reopen the issue? ;)

**Comment by pdbjjens** [comment] 2021-02-11 08:22
@Flauschi83 
Would you mind checking the iobroker log for the following message: 
"Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)"
while you have the Objects tab of the SMA-EM open and the values seem to be frozen? For this to happen you need to disable your cron restart temporarily of course.

**Comment by Flauschi83** [comment] 2021-02-11 15:54
just disabled the restart and now everything seems to work.
Due to heavy snow, the surplus is constantly 0....that despite updating ioBroker Host since last try, nothing changed.

Hopefully tomorrow the roof will be a bit clear and I can double check with surplus.

**Comment by pdbjjens** [comment] 2021-02-15 17:44
@Flauschi83 
Any news on your test? please also let us know your environment (js-controller, node, os versions)

**Comment by Flauschi83** [comment] 2021-02-15 18:06
sorry yesterday the roof went clear :/

js-controller:  3.2.16
Proxmox VM with:
    Distributor ID: Debian
    Description:    Debian GNU/Linux 9.13 (stretch)
    Release:        9.13
    Codename:       stretch
Admin 4.2.1
Node v10.23.2


and the adapter is still running. No idea what changed except the controller update some weeks ago.... sorry for the bother, but I will keep it in sight and check every now and then. Maybe @maxpd1 still has the issue?

**Comment by pdbjjens** [comment] 2021-02-15 21:47
@maxpd1 
Do you still experience this problem with  0.6.1-beta.0? If so, would you mind checking the iobroker log for the following message:
"Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)"
while you have the Objects tab of the SMA-EM open and the values seem to be frozen? For this to happen you need to disable your cron restart temporarily of course.
Please also let us know your environment (js-controller, node, os versions)

**Comment by Flauschi83** [comment] 2021-02-15 22:31
no everything is working fine and for me the issue is (however) solved.
No Cron Job. The Adapter is running since 10th Feb without restart and without any log entries.

As I would expect.

**Comment by pdbjjens** [comment] 2021-02-16 07:45
@Flauschi83 
Thank you for your confirmation. I already assumed from your previous message that the problem is solved for you. 
Actually I was addressing my question towards 
@maxpd1 
since he is the originator of this issue and I would like him to check the log.

**Comment by patrick7519** [comment] 2021-02-18 10:47
Same problem here. Adapter works betweenr 4 and 5 minutes and then a freeze. The Time stamp is red. The connection is true. 
js-controller: 3.2.16
ESXi VM with:
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10.8
Codename: buster
Admin 4.2.1
Node.js: v12.20.2
NPM: 6.14.11

**Comment by pdbjjens** [comment] 2021-02-18 13:01
@patrick7519 
Would you mind checking the iobroker log for the following message:
"Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)"
while you have the Objects tab of the SMA-EM open and the values seem to be frozen? If you do not see such message, it would be helpful for the analysis of the problem if you would provide a screenshot of the iobroker log anyhow. Especially the phase of adapter start until the lock-up happens would be of interest.
Also I would like to know which options you have enabled in the config page ( i.e. options L1, L2, L3, Extended Details ) of the SMA-EM instance.

**Comment by patrick7519** [comment] 2021-02-18 13:35
HI, i have no such messages in the iobroker log.  Attached the both requested screenshots.
![Log_Restart_SMA-EM](https://user-images.githubusercontent.com/79255287/108364573-827c2680-71f6-11eb-8ce5-b1dc2e506924.PNG)
![Setting_SMA-EM](https://user-images.githubusercontent.com/79255287/108364577-8445ea00-71f6-11eb-96dc-dc94e0a08ff0.PNG)

**Comment by pdbjjens** [comment] 2021-02-18 13:47
@patrick7519 
Thank you for the information. So it is correct that you have two SMA-EM devices and all 4 options enabled, right? Before taking the  screenshot of the log, did you have the Objects tab of the SMA-EM open and wait until the values seemed to be frozen?

**Comment by patrick7519** [comment] 2021-02-18 13:53
No, i have one SMA-EM, but the iobroker machine have two ethernet adapters. One for the LAN and the second for the DMZ. In that DMZ the SMA-EM is located. On this one SMA-EM all 4 options are enabled. Yes the object tab was open, i waited the time and make this screenshots after the frozen.

**Comment by pdbjjens** [comment] 2021-02-18 14:45
I see. That was an important clarification. Maybe the dual interfaces are the reason for the freeze. Please hold on while I am checking with my peers.

**Comment by pdbjjens** [comment] 2021-02-21 09:57
@patrick7519 
I need some further clarification: 
It seems to me that you are using the special version of SMA-EM  0.6.1-beta.0 which should fix the issue #117 which was provided on Github by TGuybrush. Is that the case ?
In your iobroker log I see that the adapter finds a EM on both of your Networks. I suppose that network 10.73.15.xxx and 10.73.16.xxx are your LAN and your DMZ. Is that true?
Since you only have one EM  on your DMZ It seems that the EM multicasts not only go into the DMZ but that your firewall also forwards them into your LAN. Can you please check whether this is the case? If it is the case, is there an option in your firewall to disable multicast forwarding into your LAN? Can you try this and check whether the adapter does not freeze in that case?

**Comment by patrick7519** [comment] 2021-02-23 07:00
Hi pdbjjens,
yes i use this version. Now it works, the problem was the multicast on both networks and this freezed the adapter. Now the multicast is only in one network segment and now it runs. The adapter shows on start both networks, but this is no problem.
Many thanks for your help and best regards

**Comment by pdbjjens** [comment] 2021-02-23 08:25
@patrick7519 
Thank you for checking this out and your positive feedback. I am glad that it works for you now.
@maxpd1 
Do you still experience this problem with 0.6.1-beta.0? Please let us know your status. Otherwise I will close this issue.

**Comment by maxpd1** [comment] 2021-02-23 12:04
Hi sorry, at the moment I am more trying to get modbus adapter running as the SMA adapter isn't delivering the information I wanted. e.g. own consumption

**Comment by pdbjjens** [comment] 2021-02-23 13:44
@maxpd1 
Thank you for your answer. I will close this issue then for now. In case you will pursue the SMA-EM at a later time again, you can reopen this issue anytime.

**Closed by pdbjjens** 2021-02-23 13:44 UTC
